// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Plip",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Plip",
            targets: ["AppModule"],
            bundleIdentifier: "com.puntawat.travelgermanyapp",
            teamIdentifier: "Y66RNXDHY4",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibrary(purposeString: "To record your memories"),
                .locationWhenInUse(purposeString: "To record your memories"),
                .faceID(purposeString: "To secure your memories.")
            ],
            appCategory: .travel
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)